[build]
  publish = "." # 或者你的构建输出目录，如 "dist"

# [[plugins]]
#  package = "@netlify/plugin-visual" # 此插件不存在

[build.environment]
  NODE_VERSION = "16" # 或更高版本

  [[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-of-service.html"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false


[[redirects]]
  from = "/collections/*"
  to = "/collections/:splat.html"
  status = 200

[[redirects]]
  from = "/products/*"
  to = "/products/:splat.html"
  status = 200

# 其他配置...
